# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClientInfo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x43lientInfo.proto\"?\n\nClientInfo\x12\x14\n\x0c\x61\x64\x64ress_ipv4\x18\x01 \x01(\x07\x12\n\n\x02id\x18\x02 \x01(\r\x12\x0f\n\x07latency\x18\x03 \x01(\rb\x06proto3')



_CLIENTINFO = DESCRIPTOR.message_types_by_name['ClientInfo']
ClientInfo = _reflection.GeneratedProtocolMessageType('ClientInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTINFO,
  '__module__' : 'ClientInfo_pb2'
  # @@protoc_insertion_point(class_scope:ClientInfo)
  })
_sym_db.RegisterMessage(ClientInfo)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CLIENTINFO._serialized_start=20
  _CLIENTINFO._serialized_end=83
# @@protoc_insertion_point(module_scope)
