# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SerialMonitorMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aSerialMonitorMessage.proto\"n\n\x14SerialMonitorMessage\x12(\n\x04type\x18\x01 \x01(\x0e\x32\x1a.SerialMonitorMessage.Type\",\n\x04Type\x12\x11\n\rQUERY_REQUEST\x10\x00\x12\x11\n\rRESET_REQUEST\x10\x01\x62\x06proto3')



_SERIALMONITORMESSAGE = DESCRIPTOR.message_types_by_name['SerialMonitorMessage']
_SERIALMONITORMESSAGE_TYPE = _SERIALMONITORMESSAGE.enum_types_by_name['Type']
SerialMonitorMessage = _reflection.GeneratedProtocolMessageType('SerialMonitorMessage', (_message.Message,), {
  'DESCRIPTOR' : _SERIALMONITORMESSAGE,
  '__module__' : 'SerialMonitorMessage_pb2'
  # @@protoc_insertion_point(class_scope:SerialMonitorMessage)
  })
_sym_db.RegisterMessage(SerialMonitorMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERIALMONITORMESSAGE._serialized_start=30
  _SERIALMONITORMESSAGE._serialized_end=140
  _SERIALMONITORMESSAGE_TYPE._serialized_start=96
  _SERIALMONITORMESSAGE_TYPE._serialized_end=140
# @@protoc_insertion_point(module_scope)
