# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WirelessClientMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ClientInfo_pb2 as ClientInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bWirelessClientMessage.proto\x1a\x10\x43lientInfo.proto\"\xfd\x01\n\x15WirelessClientMessage\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.WirelessClientMessage.Type\x12!\n\nassignment\x18\x02 \x01(\x0b\x32\x0b.ClientInfoH\x00\"\x8a\x01\n\x04Type\x12\t\n\x05NONE_\x10\x00\x12\x08\n\x04PONG\x10\x01\x12%\n!HANDSHAKE_ASSIGNMENT_CONFIRMATION\x10\x02\x12\x16\n\x12RESET_CONFIRMATION\x10\x03\x12\x15\n\x11HANDSHAKE_REQUEST\x10\x04\x12\x17\n\x13\x41RBITRATION_REQUEST\x10\x05\x42\t\n\x07\x63ontentb\x06proto3')



_WIRELESSCLIENTMESSAGE = DESCRIPTOR.message_types_by_name['WirelessClientMessage']
_WIRELESSCLIENTMESSAGE_TYPE = _WIRELESSCLIENTMESSAGE.enum_types_by_name['Type']
WirelessClientMessage = _reflection.GeneratedProtocolMessageType('WirelessClientMessage', (_message.Message,), {
  'DESCRIPTOR' : _WIRELESSCLIENTMESSAGE,
  '__module__' : 'WirelessClientMessage_pb2'
  # @@protoc_insertion_point(class_scope:WirelessClientMessage)
  })
_sym_db.RegisterMessage(WirelessClientMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIRELESSCLIENTMESSAGE._serialized_start=50
  _WIRELESSCLIENTMESSAGE._serialized_end=303
  _WIRELESSCLIENTMESSAGE_TYPE._serialized_start=154
  _WIRELESSCLIENTMESSAGE_TYPE._serialized_end=292
# @@protoc_insertion_point(module_scope)
