# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WirelessHostMessage.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ClientInfo_pb2 as ClientInfo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19WirelessHostMessage.proto\x1a\x10\x43lientInfo.proto\"\xc9\x01\n\x13WirelessHostMessage\x12\'\n\x04type\x18\x01 \x01(\x0e\x32\x19.WirelessHostMessage.Type\x12!\n\nassignment\x18\x02 \x01(\x0b\x32\x0b.ClientInfoH\x00\"[\n\x04Type\x12\x08\n\x04PING\x10\x00\x12\x18\n\x14HANDSHAKE_ASSIGNMENT\x10\x01\x12\x11\n\rRESET_REQUEST\x10\x02\x12\x1c\n\x18\x41RBITRATION_CONFIRMATION\x10\x03\x42\t\n\x07\x63ontentb\x06proto3')



_WIRELESSHOSTMESSAGE = DESCRIPTOR.message_types_by_name['WirelessHostMessage']
_WIRELESSHOSTMESSAGE_TYPE = _WIRELESSHOSTMESSAGE.enum_types_by_name['Type']
WirelessHostMessage = _reflection.GeneratedProtocolMessageType('WirelessHostMessage', (_message.Message,), {
  'DESCRIPTOR' : _WIRELESSHOSTMESSAGE,
  '__module__' : 'WirelessHostMessage_pb2'
  # @@protoc_insertion_point(class_scope:WirelessHostMessage)
  })
_sym_db.RegisterMessage(WirelessHostMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WIRELESSHOSTMESSAGE._serialized_start=48
  _WIRELESSHOSTMESSAGE._serialized_end=249
  _WIRELESSHOSTMESSAGE_TYPE._serialized_start=147
  _WIRELESSHOSTMESSAGE_TYPE._serialized_end=238
# @@protoc_insertion_point(module_scope)
